### ISSUE TITLE
Transcription errors

### ISSUE THREAD

**Issue by mkfmnn** [laserbat/bach.sed#3]
From listening to the mp3 posted on clyp.it, I noticed the following errors and wanted to report them in case they were unintentional:

* The "G" in measure 22 (1:19-1:22 in the mp3), played four times, should actually be an "A", one whole step higher.
* The high "D" in measure 31 (1:59-2:02), played four times, should actually be a "B", a minor third lower.
* Measure 33 skips two notes in the third beat of the measure (2:10).

**Comment by laserbat** [comment]
Thank you for noticing that! I'll fix it ASAP

**Comment by laserbat** [comment]
And done :)
